language: python
dist: xenial
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.7"
  - "3.8"
  - "3.9-dev" # 3.7 development branch
  - "3.10-dev" # 3.7 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "3.10-dev"
    - python: "nightly"

services:
  - postgresql
  - mysql

install:
  - pip install cookiecutter

script:
  - make test
