language: python
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch

allow_failures:
  - python: "3.6-dev"
  - python: "3.7-dev"

services:
  - postgresql

install:
  - pip install cookiecutter

script:
  - make test
